name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "44619158-c605696f-707b-451f-b982-5e90b2aa3d32" \
            --env-var productSlug=noutbuk-apple-macbook-pro-14-m4-pro-24-512gb-2024-mx2h3ua-a-space-black \
            --env-var productSlug2=noutbuk-apple-macbook-air-15-3-m4-24-512gb-2025-mc7d4ua-a-sky-blue